FROM jcrattzama/cube-in-a-box:odc1.8.3

# Let jovyan run sudo without a password.
USER root
# RUN echo "jovyan ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
# RUN chown -R jovyan /env

RUN pip3 install --upgrade pip

# Install System Dependencies #

# RUN apt-get update -y \
#   && DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing --no-install-recommends \
#   # developer convenience
#   postgresql-client-10 \
#   less \
#   vim \
#   git \
#   && rm -rf /var/lib/apt/lists/*

# End Install System Dependencies #

# Handle Rasterio Issues #

# (Option 1) If using binary rasterio package, to support HTTPS, symlink SSL certs path.
# Note that installing with `pip install --no-binary=rasterio rasterio`
# may not require this, but this is still a good safeguard to use.
# RUN mkdir -p /etc/pki/tls/certs && \
    # ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt

# (Option 2) Install rasterio from binary.
# RUN pip3 install --no-binary=rasterio rasterio==1.1.8

# End Handle Rasterio Issues #

# Install Extra Dependencies (dependencies for this particular deployment) #

# COPY extra_requirements.txt /conf/
# RUN . /env/bin/activate && pip3 install \
    # This Python packages index is Digital Earth Australia's package index.
    # Used for installing the odc-tools package (provides an `odc` module).
    # --extra-index-url="https://packages.dea.ga.gov.au" \
    # -r /conf/extra_requirements.txt

# RUN export GDAL_DATA=$(gdal-config --datadir)
# ENV LC_ALL=C.UTF-8 \
#     PATH="/env/bin:$PATH"

# Install Nbdime
# RUN pip3 install ndbime==2.1.0

# End Install Extra Dependencies #

# Setup the Open Data Cube configuration.
ARG ODC_DB_HOSTNAME="odc-db"
ARG ODC_DB_DATABASE="datacube"
ARG ODC_DB_USER="dc_user"
ARG ODC_DB_PASSWORD="localuser1234"
ARG ODC_DB_PORT="5432"
ENV ODC_DB_HOSTNAME=${ODC_DB_HOSTNAME} \
    ODC_DB_DATABASE=${ODC_DB_DATABASE} \
    ODC_DB_USER=${ODC_DB_USER} \
    ODC_DB_PASSWORD=${ODC_DB_PASSWORD} \
    ODC_DB_PORT=${ODC_DB_PORT}
RUN mkdir -p /config && echo "\
[datacube] \n\
db_hostname: ${ODC_DB_HOSTNAME} \n\
db_database: ${ODC_DB_DATABASE} \n\
db_username: ${ODC_DB_USER} \n\
db_password: ${ODC_DB_PASSWORD} \n" > /config/datacube.conf
RUN cp /config/datacube.conf /etc/datacube.conf
ENV DATACUBE_CONFIG_PATH=/config/datacube.conf

ARG NOTEBOOK_ROOT
ENV NOTEBOOK_ROOT=${NOTEBOOK_ROOT}
WORKDIR ${NOTEBOOK_ROOT}

USER jovyan
ENTRYPOINT ["/bin/tini", "--"]
CMD ["jupyter", "notebook", "--allow-root", "--ip='0.0.0.0'" "--NotebookApp.token='secretpassword'"]
