# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(default='', max_length=1000, unique=True)),
                ('latitude_max', models.FloatField(default=0)),
                ('latitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('scene_count', models.IntegerField(default=0)),
                ('pixel_count', models.IntegerField(default=0)),
                ('clean_pixel_count', models.IntegerField(default=0)),
                ('percentage_clean_pixels', models.FloatField(default=0)),
                ('acquisition_list', models.CharField(default='', max_length=100000)),
                ('clean_pixels_per_acquisition', models.CharField(default='', max_length=100000)),
                ('clean_pixel_percentages_per_acquisition', models.CharField(default='', max_length=100000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(default='', max_length=1000)),
                ('area_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=10000)),
                ('user_id', models.CharField(default='', max_length=25)),
                ('query_start', models.DateTimeField(verbose_name='query_start')),
                ('query_end', models.DateTimeField(verbose_name='query_end')),
                ('platform', models.CharField(default='', max_length=25)),
                ('product', models.CharField(default='', max_length=50)),
                ('latitude_min', models.FloatField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('baseline_method', models.CharField(default='median', max_length=50)),
                ('baseline', models.CharField(default='1,2,3,4,5,6,7,8,9,10,11,12', max_length=50)),
                ('time_start', models.CharField(default='0', max_length=5000)),
                ('time_end', models.CharField(default='0', max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(default='', max_length=1000, unique=True)),
                ('status', models.CharField(default='', max_length=100)),
                ('scenes_processed', models.IntegerField(default=0)),
                ('total_scenes', models.IntegerField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('latitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('result_path', models.CharField(default='', max_length=250)),
                ('scene_ndvi_path', models.CharField(default='', max_length=250)),
                ('baseline_ndvi_path', models.CharField(default='', max_length=250)),
                ('ndvi_percentage_change_path', models.CharField(default='', max_length=250)),
                ('result_mosaic_path', models.CharField(default='', max_length=250)),
                ('data_netcdf_path', models.CharField(default='', max_length=250)),
                ('data_path', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
