# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default='', max_length=250)),
                ('application_name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
