FROM opendatacube/cube-in-a-box
# jcrattzama/cube-in-a-box:odc1.8.3

USER root

RUN chown root:root /usr/bin/sudo
RUN chown root:root /etc/sudoers
RUN chown root:root /usr/lib/sudo/sudoers.so
RUN chown -R 0:0 /etc/sudoers.d
