# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(default='None', max_length=25, unique=True)),
                ('app_name', models.CharField(default='None', max_length=25)),
                ('type_name', models.CharField(default='None', max_length=25)),
                ('data_variable', models.CharField(default='None', max_length=25)),
                ('band_number', models.CharField(default='None', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default='', max_length=250)),
                ('application_name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(default='', max_length=250, unique=True)),
                ('area_name', models.CharField(default='', max_length=250)),
                ('latitude_min', models.FloatField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('main_imagery', models.CharField(default='', max_length=250)),
                ('detail_imagery', models.CharField(default='', max_length=250)),
                ('detail_latitude_min', models.FloatField(default=0)),
                ('detail_latitude_max', models.FloatField(default=0)),
                ('detail_longitude_min', models.FloatField(default=0)),
                ('detail_longitude_max', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_id', models.CharField(max_length=25, unique=True)),
                ('baseline_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Compositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositor_id', models.CharField(max_length=25, unique=True)),
                ('compositor_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=25, unique=True)),
                ('satellite_name', models.CharField(max_length=25)),
                ('product_prefix', models.CharField(max_length=25)),
                ('date_min', models.DateField(default=datetime.date.today, verbose_name='date_min')),
                ('date_max', models.DateField(default=datetime.date.today, verbose_name='date_min')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='satellites',
            field=models.ManyToManyField(to='data_cube_ui.Satellite'),
        ),
        migrations.AddField(
            model_name='application',
            name='areas',
            field=models.ManyToManyField(to='data_cube_ui.Area'),
        ),
        migrations.AddField(
            model_name='application',
            name='satellites',
            field=models.ManyToManyField(to='data_cube_ui.Satellite'),
        ),
    ]
